export const ambassadorsProfiles = [
    {
      name: "David Quintanilla",
      username_twitter: "@dave_quinta",
      description: `AI Developer | <a class="text-indigo-700 hover:underline cursor-pointer" href="https://twitter.com/auth0" target="_blank">@auth0 Ambassador</a>`,
      github_url: "https://github.com/davequinta",
      twitter_url: "https://twitter.com/dave_quinta",
      linkedin_url: "https://www.linkedin.com/in/david-quinta/",
      image: "/david.jpg",
    },
    {
      name: "Napoleón Pérez",
      username_twitter: "@napoperez1998",
      description: `ML Engineer | Researcher  <a class="text-indigo-700 hover:underline cursor-pointer" href="https://twitter.com/ieeetems" target="_blank">@ieeetems</a>`,
      github_url: "https://github.com/napo178",
      twitter_url: "https://twitter.com/napoperez1998",
      linkedin_url: "https://www.linkedin.com/in/napole%C3%B3n-alcides-p-194375114/",
      image: "/napoleon.jpeg",
    },
    {
      name: "Giancarlo Pablo",
      username_twitter: "@gpablo06",
      description: `Blockchain Dev <a class="text-indigo-700 hover:underline cursor-pointer" href="https://twitter.com/@API3Latam" target="_blank">@API3Latam</a>`,
      github_url: "https://github.com/gpablo6",
      twitter_url: "https://twitter.com/gpablo06",
      linkedin_url: "https://www.linkedin.com/in/gpablo6/",
      image: "/pablo.png",
    },
    {
      name: "Nelson Hernández",
      username_twitter: "@nelsoncode_dev",
      description: `Frontend Developer at <a class="text-indigo-700 hover:underline cursor-pointer" href="https://twitter.com/@denolyrics" target="_blank">@denolyrics</a> | Content Creator`,
      github_url: "https://github.com/nelsondev19",
      twitter_url: "https://twitter.com/nelsoncode_dev",
      linkedin_url: "https://www.linkedin.com/in/nelsoncode/",
      image: "/nelson.jpg",
    },
  ];
